"""Traceable focal spot analysis primitives."""

from .core import analyze
from .detection import (
    DEFAULT_DETECTION_PROFILE,
    AutomaticAnalysisProposal,
    FocalSpotCandidate,
    FocalSpotDetectionProfile,
    detect_main_focal_spot,
    propose_auto_analysis,
)
from .input import DecodeOutcome, decode_png
from .validation import (
    run_complete_validation,
    run_identity_validation,
    run_issue10_validation,
    run_performance_baseline,
    run_real_fixture_validation,
    run_report_validation,
    run_validation,
)
from .report import (
    BatchExportSummary,
    ExportOutcome,
    ReportPackage,
    ReportSpecification,
    ReportWorkItem,
    batch_export_reports,
    export_batch_reports,
    export_reports_batch,
    is_report_eligible,
    prepare_report,
    report_text,
    write_report,
)
from .profiles import (
    ProfileValidationError,
    advanced_settings_status,
    default_model_values,
    default_preprocessing_values,
    get_analysis_profile,
    resolve_preprocessing,
    validate_advanced_settings,
)
from .models import (
    AnalysisConfiguration,
    AnalysisModel,
    AnalysisOutcome,
    AnalysisRecord,
    AnalysisRegion,
    FlowStatus,
    InputImage,
    MeasurementStatus,
    Metric,
    PreprocessingConfiguration,
    SpatialCalibration,
)

__all__ = [
    "AnalysisConfiguration",
    "AnalysisModel",
    "AutomaticAnalysisProposal",
    "DEFAULT_DETECTION_PROFILE",
    "FocalSpotCandidate",
    "FocalSpotDetectionProfile",
    "DecodeOutcome",
    "AnalysisOutcome",
    "AnalysisRecord",
    "AnalysisRegion",
    "FlowStatus",
    "InputImage",
    "MeasurementStatus",
    "Metric",
    "PreprocessingConfiguration",
    "SpatialCalibration",
    "ProfileValidationError",
    "advanced_settings_status",
    "default_model_values",
    "default_preprocessing_values",
    "get_analysis_profile",
    "resolve_preprocessing",
    "validate_advanced_settings",
    "analyze",
    "decode_png",
    "detect_main_focal_spot",
    "propose_auto_analysis",
    "run_complete_validation",
    "run_identity_validation",
    "run_issue10_validation",
    "run_performance_baseline",
    "run_real_fixture_validation",
    "run_report_validation",
    "run_validation",
    "BatchExportSummary",
    "ExportOutcome",
    "ReportPackage",
    "ReportSpecification",
    "ReportWorkItem",
    "batch_export_reports",
    "export_batch_reports",
    "export_reports_batch",
    "is_report_eligible",
    "prepare_report",
    "report_text",
    "write_report",
]
